title: American Sign Language Alphabet Classifier
description: Classify American Sign Language using deep learning
about:


  This is an American Sign Language Alphabet Images Classifier using Deep Learning built on top of Pytorch.

  This project was built upon the project that was built by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    




code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: A
    url: https://www.lifeprint.com/asl101/signjpegs/a/a.jpg
  - name: X
    url: https://www.lifeprint.com/asl101/signjpegs/x/x2.jpg
  - name: O
    url: https://www.lifeprint.com/asl101/signjpegs/o/o1.jpg
